FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["SecureDevOps.API.csproj", "."]
RUN dotnet restore "SecureDevOps.API.csproj"

COPY . .

RUN dotnet publish "SecureDevOps.API.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "SecureDevOps.API.dll"]